# Generated by Django 4.0.6 on 2022-08-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='token',
            field=models.CharField(default=12, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='verify',
            field=models.BooleanField(default=False),
        ),
    ]
